### ISSUE TITLE
IPv6 and ICMPv6 support

### ISSUE THREAD

**Issue by Grinnz** [yanick/netpacket#8]
I notice there's a link in the documentation to a blog (from 11 years ago) with IPv6 and ICMPv6 modules as a patch... but these could easily be available on CPAN (and probably more up to date). I'm willing to work on this, would you prefer a PR to this dist or for me to release it as a separate dist?

**Comment by yanick** [comment]
On 2015-10-30 06:25 PM, Dan Book wrote:
> I notice there's a link in the documentation to a blog (from 11 years
> ago) with IPv6 and ICMPv6 modules as a patch... but these could easily
> be available on CPAN (and probably updated a bit). I'm willing to work
> on this, would you prefer a PR to this dist or for me to release it as a
> separate dist?

I think the license of the patches does not align perfectly with the
license of the main module. If that's indeed the case, a separate dist
would be best.

Thanks!
`/anick

**Comment by Grinnz** [comment]
The license of the patches is frankly unusable. I would be more inclined to just reimplement the modules under a slightly different name.

**Comment by yanick** [comment]
On 2015-10-31 11:36 PM, Dan Book wrote:
> The license of the patches is frankly unusable. I would be more inclined
> to just reimplement the modules under a slightly different name.

Reimplementing the modules whenever I'd get the chance was also the
option I was going for. Of course, that "whenever" didn't materialize
itself yet... :-P

**Comment by yanick** [comment]
Gloriously dealt with in #10
